apiVersion: v1
kind: Secret
metadata:
  name: zebra
type: Opaque
data:
  portz: ODA4MAo=
  powered-by: RGVpcyBhbmQuLi55b3UhCg==
---
apiVersion: v1
kind: Pod
metadata:
  name: croc-hunter
  labels:
    app: croc-hunter
spec:
  containers:
    - name: croc-hunter
      image: quay.io/lachie83/croc-hunter:v1
      ports:
        - containerPort: 8080
      volumeMounts:
      - name: secret-volume
        mountPath: "/etc/secret"
        readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: zebra
