apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  portz: ODA4MAo=
  powered-by: RGVpcyBhbmQuLi55b3UhCg==
---
apiVersion: v1
kind: Pod
metadata:
  name: example-go-secrets
  labels:
    app: webapp
    role: frontend
spec:
  containers:
    - name: example-go
      image: deis/example-go
      env:
      - name: POWERED_BY
        valueFrom:
          secretKeyRef:
            name: example-go-secret
            key: powered-by
      - name: PORT
        valueFrom:
          secretKeyRef:
            name: example-go-secret
            key: port
