apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /dataz
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-volumes
  labels:
    app: webapp
    role: frontend
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - mountPath: /dataz
        name: my-pd
      env:
      - name: PORT
        value: "8080"
  volumes:
  - name: my-pd
    persistentVolumeClaim:
      claimName: i-need-a-claim
